name = "yog_io"
version = "0.6.0"

targets = ["erlang", "javascript"]
description = "Graph file format I/O for the yog graph library - GraphML and GDF support"
licences = ["Apache-2.0"]
repository = { type = "github", user = "code-shoily", repo = "yog_io" }
links = [{ title = "Website", href = "https://github.com/code-shoily/yog_io" }]

[dependencies]
gleam_stdlib = ">= 0.69.0 and < 1.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
simplifile = ">= 1.0.0 and < 3.0.0"
xmlm = ">= 1.0.1 and < 2.0.0"
yog = ">= 5.0.0 and < 6.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
typescript_declarations = true