import gleam/dict
import gleam/list
import gleeunit/should
import yog/model.{Directed, Undirected}
import yog_io/matrix_market as mtx_io

pub fn parse_coordinate_general_real_test() {
  let content =
    "%%MatrixMarket matrix coordinate real general\n3 3 2\n1 2 0.5\n2 3 1.2\n"
  let assert Ok(result) = mtx_io.from_string(content)
  let graph = result.graph

  dict.size(graph.nodes) |> should.equal(3)
  model.edge_count(graph) |> should.equal(2)

  let succ1 = model.successors(graph, 1)
  list.key_find(succ1, 2) |> should.equal(Ok(0.5))
}

pub fn parse_coordinate_symmetric_real_test() {
  let content =
    "%%MatrixMarket matrix coordinate real symmetric\n3 3 2\n1 2 0.5\n2 3 1.2\n"
  let assert Ok(result) = mtx_io.from_string(content)
  let graph = result.graph

  dict.size(graph.nodes) |> should.equal(3)
  model.edge_count(graph) |> should.equal(2)
  graph.kind |> should.equal(Undirected)

  let succ1 = model.successors(graph, 1)
  list.key_find(succ1, 2) |> should.equal(Ok(0.5))
}

pub fn serialize_coordinate_test() {
  let graph =
    model.new(Directed)
    |> model.add_node(1, Nil)
    |> model.add_node(2, Nil)
  let assert Ok(graph) = model.add_edge(graph, from: 1, to: 2, with: 1.0)

  let str = mtx_io.serialize(graph)
  str
  |> should.equal(
    "%%MatrixMarket matrix coordinate real general\n% Generated by Yog\n2 2 1\n1 2 1.0\n",
  )
}

pub fn from_string_integer_test() {
  let content =
    "%%MatrixMarket matrix coordinate integer general\n2 2 1\n1 2 5\n"
  let assert Ok(result) = mtx_io.from_string(content)
  let graph = result.graph

  let succ1 = model.successors(graph, 1)
  list.key_find(succ1, 2) |> should.equal(Ok(5.0))
}
